version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  fabric_test:
    external: true

services:
  explorer-db:
    image: hyperledger/explorer-db:latest
    container_name: explorer-db
    hostname: explorer-db
    environment:
      - POSTGRES_DB=fabricexplorer
      - POSTGRES_USER=hppoc
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric_test

  explorer:
    image: hyperledger/explorer:latest
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=explorer-db
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile.json:/opt/explorer/app/platform/fabric/connection-profile.json
      - ../fabric/test-network:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8090:8080
    depends_on:
      explorer-db:
        condition: service_healthy
    networks:
      - fabric_test
